// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOr_8iHkJdhq70e07cP3NG7so8w_Or9Cs',
    appId: '1:518313850834:web:ced3004c5a4de6d32bba0b',
    messagingSenderId: '518313850834',
    projectId: 'student-bus-pass-ajce',
    authDomain: 'student-bus-pass-ajce.firebaseapp.com',
    storageBucket: 'student-bus-pass-ajce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2fNCTJl_CWMQQiAoEgWCO053rqR2-WI',
    appId: '1:518313850834:android:49c1f5d2e2acbe042bba0b',
    messagingSenderId: '518313850834',
    projectId: 'student-bus-pass-ajce',
    storageBucket: 'student-bus-pass-ajce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT-HsB5DGFN120d-xEM1uGQtB6oWoI0tU',
    appId: '1:518313850834:ios:bf6ee9e17d27f6602bba0b',
    messagingSenderId: '518313850834',
    projectId: 'student-bus-pass-ajce',
    storageBucket: 'student-bus-pass-ajce.firebasestorage.app',
    iosBundleId: 'com.example.studentBusPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT-HsB5DGFN120d-xEM1uGQtB6oWoI0tU',
    appId: '1:518313850834:ios:bf6ee9e17d27f6602bba0b',
    messagingSenderId: '518313850834',
    projectId: 'student-bus-pass-ajce',
    storageBucket: 'student-bus-pass-ajce.firebasestorage.app',
    iosBundleId: 'com.example.studentBusPass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOr_8iHkJdhq70e07cP3NG7so8w_Or9Cs',
    appId: '1:518313850834:web:1b5ca026686a64a22bba0b',
    messagingSenderId: '518313850834',
    projectId: 'student-bus-pass-ajce',
    authDomain: 'student-bus-pass-ajce.firebaseapp.com',
    storageBucket: 'student-bus-pass-ajce.firebasestorage.app',
  );
}
